title: Balyogi Mohan Dash
logo: images/1709641432104.jpeg
description: I’m a PhD Data Scientist focused on NLP and Computer Vision because I believe AI can make industrial systems smarter and more reliable. My passion lies in solving real-world problems, like predicting equipment failures, using advanced techniques like deep learning and XAI. Through my research and projects, I aim to bridge the gap between AI innovation and practical applications that can transform industries.
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
