title: Balyogi Mohan Dash
logo: images/1709641432104.jpeg
description: Artificial intelligence researcher with over 3 years of experience, including 2.5 years in academic research and 7 months in industrial R&D. I have collaborated with leading companies such as SNCF, Renault, Thales, and Safran to develop cutting-edge anomaly detection models and applied generative AI to enhance the robustness of deep learning models. Additionally, I create educational content on AI and machine learning on YouTube, where I have grown a community of 1,500+ subscribers.
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
